package ch5.model;
// Generated Mar 14, 2016 2:12:22 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * SalariesId generated by hbm2java
 */
public class SalariesId  implements java.io.Serializable {


     private int empNo;
     private Date fromDate;

    public SalariesId() {
    }

    public SalariesId(int empNo, Date fromDate) {
       this.empNo = empNo;
       this.fromDate = fromDate;
    }
   
    public int getEmpNo() {
        return this.empNo;
    }
    
    public void setEmpNo(int empNo) {
        this.empNo = empNo;
    }
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SalariesId) ) return false;
		 SalariesId castOther = ( SalariesId ) other; 
         
		 return (this.getEmpNo()==castOther.getEmpNo())
 && ( (this.getFromDate()==castOther.getFromDate()) || ( this.getFromDate()!=null && castOther.getFromDate()!=null && this.getFromDate().equals(castOther.getFromDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEmpNo();
         result = 37 * result + ( getFromDate() == null ? 0 : this.getFromDate().hashCode() );
         return result;
   }   


}


