package spring.demo.model;

// Generated Mar 18, 2015 12:15:31 PM by Hibernate Tools 4.3.1

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Amphures generated by hbm2java
 */
@Entity
@Table(name="amphures")
public class Amphures implements java.io.Serializable {

	@Id
	@Column(name="AMPHUR_ID")
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int amphurId;
	
	@ManyToOne
	@JoinColumn(name="PROVINCE_ID")
	private Provinces provinces;
	
	@Column(name="AMPHUR_CODE")
	private String amphurCode;
	
	@Column(name="AMPHUR_NAME")
	private String amphurName;
	
	@Column(name="GEO_ID")
	private int geoId;
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "amphures")
	@Fetch(value = FetchMode.SUBSELECT)
	private List<Districts> districtses ;

	public Amphures() {
	}

	public Amphures(Provinces provinces, String amphurCode, String amphurName, int geoId) {
		this.provinces = provinces;
		this.amphurCode = amphurCode;
		this.amphurName = amphurName;
		this.geoId = geoId;
	}

	public Amphures(Provinces provinces, String amphurCode, String amphurName, int geoId, List<Districts> districtses) {
		this.provinces = provinces;
		this.amphurCode = amphurCode;
		this.amphurName = amphurName;
		this.geoId = geoId;
		this.districtses = districtses;
	}

	public int getAmphurId() {
		return this.amphurId;
	}

	public void setAmphurId(int amphurId) {
		this.amphurId = amphurId;
	}

	public Provinces getProvinces() {
		return this.provinces;
	}

	public void setProvinces(Provinces provinces) {
		this.provinces = provinces;
	}

	public String getAmphurCode() {
		return this.amphurCode;
	}

	public void setAmphurCode(String amphurCode) {
		this.amphurCode = amphurCode;
	}

	public String getAmphurName() {
		return this.amphurName;
	}

	public void setAmphurName(String amphurName) {
		this.amphurName = amphurName;
	}

	public int getGeoId() {
		return this.geoId;
	}

	public void setGeoId(int geoId) {
		this.geoId = geoId;
	}

	public List<Districts> getDistrictses() {
		return this.districtses;
	}

	public void setDistrictses(List<Districts> districtses) {
		this.districtses = districtses;
	}

}
