package spring.demo.model;

// Generated Mar 18, 2015 12:15:31 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Geography generated by hbm2java
 */
@Entity
@Table(name="geography")
public class Geography implements java.io.Serializable {

	@Id
	@Column(name="GEO_ID")
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int id;
	
	@Column(name="GEO_NAME")
	private String geoName;
	
	@Transient
	private List<Provinces> provinceses;

	public Geography() {
	}

	public Geography(String geoName) {
		this.geoName = geoName;
	}

	public Geography(String geoName, List<Provinces> provinceses) {
		this.geoName = geoName;
		this.provinceses = provinceses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getGeoName() {
		return this.geoName;
	}

	public void setGeoName(String geoName) {
		this.geoName = geoName;
	}

	public List<Provinces> getProvinceses() {
		return this.provinceses;
	}

	public void setProvinceses(List<Provinces> provinceses) {
		this.provinceses = provinceses;
	}

}
