package spring.demo.model;

// Generated Mar 18, 2015 12:15:31 PM by Hibernate Tools 4.3.1

/**
 * Temples generated by hbm2java
 */
public class Temples implements java.io.Serializable {

	private Integer TId;
	private String TName;
	private String TSect;
	private String TNum;
	private String TMoo;
	private String TSoi;
	private String TRoad;
	private String district;
	private String buddGeo;
	private String TPhone1;
	private String TPhone2;
	private String fax;
	private String website;
	private String email;
	private String googleMap;

	public Temples() {
	}

	public Temples(String TName, String TSect, String TNum, String district, String buddGeo) {
		this.TName = TName;
		this.TSect = TSect;
		this.TNum = TNum;
		this.district = district;
		this.buddGeo = buddGeo;
	}

	public Temples(String TName, String TSect, String TNum, String TMoo, String TSoi, String TRoad, String district,
			String buddGeo, String TPhone1, String TPhone2, String fax, String website, String email, String googleMap) {
		this.TName = TName;
		this.TSect = TSect;
		this.TNum = TNum;
		this.TMoo = TMoo;
		this.TSoi = TSoi;
		this.TRoad = TRoad;
		this.district = district;
		this.buddGeo = buddGeo;
		this.TPhone1 = TPhone1;
		this.TPhone2 = TPhone2;
		this.fax = fax;
		this.website = website;
		this.email = email;
		this.googleMap = googleMap;
	}

	public Integer getTId() {
		return this.TId;
	}

	public void setTId(Integer TId) {
		this.TId = TId;
	}

	public String getTName() {
		return this.TName;
	}

	public void setTName(String TName) {
		this.TName = TName;
	}

	public String getTSect() {
		return this.TSect;
	}

	public void setTSect(String TSect) {
		this.TSect = TSect;
	}

	public String getTNum() {
		return this.TNum;
	}

	public void setTNum(String TNum) {
		this.TNum = TNum;
	}

	public String getTMoo() {
		return this.TMoo;
	}

	public void setTMoo(String TMoo) {
		this.TMoo = TMoo;
	}

	public String getTSoi() {
		return this.TSoi;
	}

	public void setTSoi(String TSoi) {
		this.TSoi = TSoi;
	}

	public String getTRoad() {
		return this.TRoad;
	}

	public void setTRoad(String TRoad) {
		this.TRoad = TRoad;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getBuddGeo() {
		return this.buddGeo;
	}

	public void setBuddGeo(String buddGeo) {
		this.buddGeo = buddGeo;
	}

	public String getTPhone1() {
		return this.TPhone1;
	}

	public void setTPhone1(String TPhone1) {
		this.TPhone1 = TPhone1;
	}

	public String getTPhone2() {
		return this.TPhone2;
	}

	public void setTPhone2(String TPhone2) {
		this.TPhone2 = TPhone2;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGoogleMap() {
		return this.googleMap;
	}

	public void setGoogleMap(String googleMap) {
		this.googleMap = googleMap;
	}

}
