package com.spring.model;

// Generated Mar 13, 2015 12:01:45 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name="departments")
public class Departments implements java.io.Serializable {

	private String deptNo;
	private String deptName;
	private Set deptEmps = new HashSet(0);
	private Set deptManagers = new HashSet(0);

	public Departments() {
	}

	public Departments(String deptNo, String deptName) {
		this.deptNo = deptNo;
		this.deptName = deptName;
	}

	public Departments(String deptNo, String deptName, Set deptEmps, Set deptManagers) {
		this.deptNo = deptNo;
		this.deptName = deptName;
		this.deptEmps = deptEmps;
		this.deptManagers = deptManagers;
	}

	public String getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(String deptNo) {
		this.deptNo = deptNo;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public Set getDeptEmps() {
		return this.deptEmps;
	}

	public void setDeptEmps(Set deptEmps) {
		this.deptEmps = deptEmps;
	}

	public Set getDeptManagers() {
		return this.deptManagers;
	}

	public void setDeptManagers(Set deptManagers) {
		this.deptManagers = deptManagers;
	}

}
