package com.spring.model;

// Generated Mar 13, 2015 12:01:45 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Titles generated by hbm2java
 */
@Entity
@Table(name="titles")
public class Titles implements java.io.Serializable {

	private TitlesId id;
	private Employees employees;
	private Date toDate;

	public Titles() {
	}

	public Titles(TitlesId id, Employees employees) {
		this.id = id;
		this.employees = employees;
	}

	public Titles(TitlesId id, Employees employees, Date toDate) {
		this.id = id;
		this.employees = employees;
		this.toDate = toDate;
	}

	public TitlesId getId() {
		return this.id;
	}

	public void setId(TitlesId id) {
		this.id = id;
	}

	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

}
