package spring.demo.model;

// Generated Mar 18, 2015 12:15:31 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Amphures generated by hbm2java
 */
public class Amphures implements java.io.Serializable {

	private Integer amphurId;
	private Provinces provinces;
	private String amphurCode;
	private String amphurName;
	private int geoId;
	private Set districtses = new HashSet(0);

	public Amphures() {
	}

	public Amphures(Provinces provinces, String amphurCode, String amphurName, int geoId) {
		this.provinces = provinces;
		this.amphurCode = amphurCode;
		this.amphurName = amphurName;
		this.geoId = geoId;
	}

	public Amphures(Provinces provinces, String amphurCode, String amphurName, int geoId, Set districtses) {
		this.provinces = provinces;
		this.amphurCode = amphurCode;
		this.amphurName = amphurName;
		this.geoId = geoId;
		this.districtses = districtses;
	}

	public Integer getAmphurId() {
		return this.amphurId;
	}

	public void setAmphurId(Integer amphurId) {
		this.amphurId = amphurId;
	}

	public Provinces getProvinces() {
		return this.provinces;
	}

	public void setProvinces(Provinces provinces) {
		this.provinces = provinces;
	}

	public String getAmphurCode() {
		return this.amphurCode;
	}

	public void setAmphurCode(String amphurCode) {
		this.amphurCode = amphurCode;
	}

	public String getAmphurName() {
		return this.amphurName;
	}

	public void setAmphurName(String amphurName) {
		this.amphurName = amphurName;
	}

	public int getGeoId() {
		return this.geoId;
	}

	public void setGeoId(int geoId) {
		this.geoId = geoId;
	}

	public Set getDistrictses() {
		return this.districtses;
	}

	public void setDistrictses(Set districtses) {
		this.districtses = districtses;
	}

}
