package spring.demo.model;

// Generated Mar 18, 2015 12:15:31 PM by Hibernate Tools 4.3.1

/**
 * Districts generated by hbm2java
 */
public class Districts implements java.io.Serializable {

	private Integer districtId;
	private Amphures amphures;
	private String districtCode;
	private String districtName;

	public Districts() {
	}

	public Districts(Amphures amphures, String districtCode, String districtName) {
		this.amphures = amphures;
		this.districtCode = districtCode;
		this.districtName = districtName;
	}

	public Integer getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

	public Amphures getAmphures() {
		return this.amphures;
	}

	public void setAmphures(Amphures amphures) {
		this.amphures = amphures;
	}

	public String getDistrictCode() {
		return this.districtCode;
	}

	public void setDistrictCode(String districtCode) {
		this.districtCode = districtCode;
	}

	public String getDistrictName() {
		return this.districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}

}
