package spring.demo.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated Mar 18, 2015 12:15:31 PM by Hibernate Tools 4.3.1

/**
 * Zipcodes generated by hbm2java
 */

@Entity
@Table(name="zipcodes")
public class Zipcodes  {//implements java.io.Serializable

	@Id
	@Column(name="id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int id;
	
	@Column(name="district_code")
	private String districtCode;
	
	@Column(name="zipcode")
	private String zipcode;

	public Zipcodes() {
	}

	public Zipcodes(String districtCode, String zipcode) {
		this.districtCode = districtCode;
		this.zipcode = zipcode;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDistrictCode() {
		return this.districtCode;
	}

	public void setDistrictCode(String districtCode) {
		this.districtCode = districtCode;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

}
